# lv 1
# 과일로 만든 아이스크림 고르기 

SELECT FLAVOR 
FROM FIRST_HALF
WHERE FLAVOR IN (
    SELECT FLAVOR 
    FROM  ICECREAM_INFO
    WHERE INGREDIENT_TYPE = "fruit_based"
) 
AND TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC;